### ISSUE TITLE
can not convert float to the same or more number of bit fixed point 

### ISSUE THREAD

**Issue by jingpengw** [JuliaMath/FixedPointNumbers.jl#102]
this works in Julia 0.6.2:

```julia
Float32(1.0) |> N0f8
Float32(1.0) |> N0f16
```
this will not work
```julia
Float32(1.0) |> N0f32
Float32(1.0) |> N0f64
Float64(1.0) |> N0f64
```
It looks like when the number of bits is the same or larger, it won’t work.
error message:

ArgumentError: FixedPointNumbers.Normed{UInt64,64} is a 64-bit type representing 0 values from 0.0 to 1.0; cannot represent 1.0

**Comment by giordano** [comment]
I just run into the same error.  The problem is in `_convert(::Type{U}, ::Type{T}, x) where {U <: Normed,T}` function:
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/cf9ebc49d5eaef7e1d8a348762e9a820b6885f3c/src/normed.jl#L52-L55
E.g., in
```julia
FixedPointNumbers._convert(N0f64, FixedPointNumbers.rawtype(N0f64), 1.0)
```
the `y` variable is equal to
```julia
julia> y = round(FixedPointNumbers.widen1(FixedPointNumbers.rawone(N0f64)) * 1.0)
1.8446744073709552e19
```
which is larger than the maximum number that can be represented with `UInt64`:
```julia
julia> big(typemax(UInt64))
18446744073709551615
```

Maybe it's worth checking if the `x` argument is one?

**Comment by kimikage** [comment]
> Maybe it's worth checking if the x argument is one?

FYI, since the length of the mantissa part of `Float32` is `23 (+1)` bits, this is not a problem just when `x` argument is one.
```julia
julia> for f=1:32; Float32(exp2(32-f)) |> Normed{UInt32,f};end
ERROR: ArgumentError: Normed{UInt32,25} is a 32-bit type representing 4294967296 values from 0.0 to 128.0; cannot represent 128.0
```

Similarly, the length of the mantissa part of `Float64` is `52 (+1)` bits.
```julia
julia> for f=1:64; Float64(exp2(64-f)) |> Normed{UInt64,f};end
ERROR: ArgumentError: Normed{UInt64,54} is a 64-bit type representing 0 values from 0.0 to 1024.0; cannot represent 1024.0
```
Fixing this problem may be useful for the round trip testing to check the conversions.

**Comment by kimikage** [comment]
PR #131  does not change the `rem`.

> Therefore, this does not fix the problems such as:
> ```julia
> julia> using Colors
> 
> julia> white = parse(RGB{Float32}, "white")
> RGB{Float32}(1.0f0,1.0f0,1.0f0)
> 
> julia> convert(RGB{N0f32}, white)
> RGB{N0f32}(0.0,0.0,0.0)
> ```

_Originally posted by @kimikage in https://github.com/JuliaMath/FixedPointNumbers.jl/pull/131#issuecomment-547238807_

When you are faced by a problem with `rem`, please report it as a *new* issue.
