### ISSUE TITLE
Precision when converting a normed value

### ISSUE THREAD

**Issue by Cody-G** [JuliaMath/FixedPointNumbers.jl#118]
I was surprised to find that converting an integer-based normed value to `Float64` is not equivalent to dividing out the integer:

```julia
julia> Float64(reinterpret(Normed{UInt16, 16}, UInt16(100))) == 100/2^16
false
```

Is this by design?  I assumed the Float64 conversion would just do the division internally.

**Comment by timholy** [comment]
It's `100/(2^16 -1)`. Basically, for 8-bit you want 255->1.0.

**Comment by Cody-G** [comment]
Doh, that makes sense, thank you!
