### ISSUE TITLE
isinteger(::Normed) incorrect

### ISSUE THREAD

**Issue by cjdoris** [JuliaMath/FixedPointNumbers.jl#120]
The code currently assumes that the denominator is `2^f`, which is not the case for `Normed`. e.g.
```
julia> isinteger(Normed{UInt8,7}(1))
false
```

I believe you need to change
```julia
isinteger(x::FixedPoint{T,f}) where {T,f} = (x.i&(1<<f-1)) == 0
```
to
```julia
isinteger(x::Fixed{T,f}) where {T,f} = (x.i&(1<<f-1)) == 0
isinteger(x::Normed{T,f}) where {T,f} = (x.i%(1<<f-1)) == 0
```

**Comment by johnnychen94** [comment]
This looks good (though I don't quite understand the magic shifting operations here), could you open a PR on this?

Thanks
