### ISSUE TITLE
mixing Fixed and Normed

### ISSUE THREAD

**Issue by rapus95** [JuliaMath/FixedPointNumbers.jl#126]
I recently had to add several differences of `N0f8` values to finally take the `abs` of it. Thus I tried to do
```julia
#a,b of type N0f8
x = zero(Q7f8)
x += a - b
```
which probably would've failed due to the difference being negative and thus not representable.
Thus the next step for me would've been to convert `a,b` to `Q7f8` which didn't work.

Thus my question: Is there any reason why we can't mix up these types?
btw `promote(N0f8(.5), Q7f8(.5))` throws an error.

**Comment by johnnychen94** [comment]
An interesting result (perhaps a bug) related to this is:

```julia
julia> promote_type(UInt8, Int8)
UInt8

julia> UInt8(1) - Int8(2)
0xff
```

**Comment by timholy** [comment]
We should define promotions that make sense. Care to give it a crack?

In practice, the two number types are slightly different: `N1f7` is scaled by 1/127, but `Q0f7` is scaled by `1/128`. What this means is that arithmetic may be faster if you first convert everything to `Float32`, and then store the final result in whatever format you want.
