### ISSUE TITLE
Optimizing `Normed` -> `Normed` conversions

### ISSUE THREAD

**Issue by kimikage** [JuliaMath/FixedPointNumbers.jl#140]
As I suggested [here](https://github.com/JuliaMath/FixedPointNumbers.jl/pull/131#discussion_r341069209), the current `Normed` -> `Normed` conversions are inefficient in some cases.

https://github.com/JuliaMath/FixedPointNumbers.jl/blob/8d177395f327abe8cf9725b81a3b302fab9c856b/src/normed.jl#L41-L46

The current conversion method has two problems:
1. It always checks the input range even if there is no need, and may throw the exception.
2. It always uses floating-point operations even if  there is no need.

The former means that the method is not SIMD-suitable.
Regarding the latter, the conversion between types with the same `f` is already specialized.
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/ee5bd547bf73cf9ec6b976088c0c2565630f4ea5/src/normed.jl#L13
There is also the `N0f8`->`N0f16` specialization. (I wonder why.)
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/ee5bd547bf73cf9ec6b976088c0c2565630f4ea5/src/normed.jl#L47

I do not think these are urgent problems. However, the optimization may be useful *in the future* to speed up the accumulation (`reduce`). And I just found a (ugly) [workaround](https://github.com/JuliaMath/FixedPointNumbers.jl/issues/129#issuecomment-554357889) for the constant division problem, so I am writing this issue as a memorandum or reminder.

The figures below visualize the cases where the optimization is available.
- The positive (greenish) area means that the conversion is overflow-safe (i.e. there is no need for the range checking).
- The negative (reddish) area means that the conversion is unsafe (i.e. it may throw the exception).
- The deep-colored cells means that the conversion does not need floating-point operations.
  - As mentioned above, the `f1 == f2` *lines* are already supported.

![n8_n16](https://user-images.githubusercontent.com/12679384/69210671-ddac0d00-0b9e-11ea-9966-f0d6ceba48d1.png)
![n8_n32](https://user-images.githubusercontent.com/12679384/69210679-e43a8480-0b9e-11ea-9e17-779246bdf4b1.png)
![n16_n32](https://user-images.githubusercontent.com/12679384/69210690-e997cf00-0b9e-11ea-9284-b6e7978ffbc2.png)

You can get the result of other cases with the following script:
```julia
using Gadfly, Colors

set_default_plot_size(15cm, 8cm)

function mat(dest, src)
    b1, b2 = 8*sizeof(dest), 8*sizeof(src)
    if b1 > b2 # widening
        safe = [b1-f1 > b2-f2 || b2 == f2 ? 1 : -1 for f2=1:b2, f1=1:b1]
    else
        safe = [b1-f1 >= b2-f2 ? 1 : -1 for f2=1:b2, f1=1:b1]
    end
    safe .* [isinteger(f1/f2) ? f2/f1 : 1/36 for f2=1:b2, f1=1:b1]
end;

function plot_mat(dest, src)
    s = Scale.color_continuous(
        colormap=Scale.lab_gradient(LCHab(0, 100, 20), "white", LCHab(30, 100, 200)),
        minvalue=-1, maxvalue=1)
    m = mat(dest, src)
    spy(m, 
        Guide.title("Normed{$src,f2} -> Normed{$dest,f1}"),
        Guide.xlabel("f1"), Guide.xticks(ticks=axes(m, 2)),
        Guide.ylabel("f2"), Guide.yticks(ticks=axes(m, 1)),
        Guide.colorkey(title="scale"), s,
        Theme(plot_padding=[0mm,2mm,5mm,0mm]))
end;

plot_mat(UInt16, UInt8)
plot_mat(UInt32, UInt8)
plot_mat(UInt32, UInt16)
```

**Edit:** ~The *safe* areas are wrong. I forgot to take account of the "carry" or "overlapping". I will soon fix the figures and the script above.~ Updated.

**Comment by timholy** [comment]
> There is also the N0f8->N0f16 specialization. (I wonder why.)

I can't remember for sure, it seemed important at the time :smile:. (Probably, performance.) But it's certainly more specific than needed. Julia's compiler was not what it is now, so the implementations in #138 probably would have resulted in a big branch.

And I agree, Normed->Normed conversions may be a good way to improve `reduce`. Kudos as always for looking into this!

**Comment by kimikage** [comment]
See also: #97 (It seems to mainly focus on `Fixed`.)
