### ISSUE TITLE
Performance regression in `Normed` -> `Float` conversions  on Julia v1.3.0

### ISSUE THREAD

**Issue by kimikage** [JuliaMath/FixedPointNumbers.jl#144]
I have confirmed that Julia v1.2.0 and v1.3.0 give almost similar results on `Normed`->`Float` conversions (#129, #138). However, I found the performance regression (~2x - 3x slower) on x84_64 machines in the following cases:
- `Vec4{N0f32}` -> `Vec4{Float32}`
- `Vec4{N0f64}` -> `Vec4{Float32}`
- `Vec4{N0f64}` -> `Vec4{Float64}`

(cf. https://github.com/JuliaMath/FixedPointNumbers.jl/issues/129#issuecomment-544244496)

I'm *not* going to rush to investigate the cause or fix this problem. I  submit this issue as a placeholder in case any useful information is found.

**Comment by timholy** [comment]
I think those types are very niche. I'm not that worried.

**Comment by kimikage** [comment]
I agree, but my concern is the cause rather than the result. The investigation may help improve other methods (e.g. [`Fixed` -> `Float` conversions](https://github.com/JuliaMath/FixedPointNumbers.jl/issues/129#issuecomment-555594839)).

```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### Matrix of Vec4 (unit: μs)

|w64|`Float32` v1.2.0|`Float32` v1.3.0||`Float64` v1.2.0|`Float64` v1.3.0|
|:-------|--------:|--------:|-|--------:|--------:|
|`N0f8`  |   3.814 |   3.571 | |   4.499 |   5.725 |
|`N5f3`  |   3.786 |   3.457 | |   5.400 |   5.533 |
|`N0f16` |   4.000 |   3.871 | |   5.100 |   6.100 |
|`N13f3` |   3.800 |   3.700 | |   4.800 |   6.333 |
|`N0f32` |   4.583 | *13.599*| |   5.599 |   6.767 |
|`N8f24` |   5.033 |   4.243 | |   7.800 |   8.134 |
|`N29f3` |   4.933 |   4.300 | |   6.600 |   6.367 |
|`N0f64` |  13.399 | *23.000*| |  12.600 | *21.699*|
|`N61f3` |  13.200 |  12.199 | |  11.400 |  11.599 |
|`N0f128`|  38.800 |  37.099 | |  35.600 |  35.200 |
|`N125f3`|  44.099 |  40.199 | |  38.500 |  40.299 |
