### ISSUE TITLE
Float64->UInt8 unexpectedly get affected in v0.7.0

### ISSUE THREAD

**Issue by johnnychen94** [JuliaMath/FixedPointNumbers.jl#164]
Any ideas of how the results are changed upgrading from v0.6.1 to v0.7.0? I'll check that later if nobody does... (Catching a cold now and my mind goes blank...)

Here is the minimal codes I can provide so far:

```julia
using ImageCore, TestImages, SHA
img = RGB{Float64}.(testimage("lena_color_256"))
img_str = bytes2hex(sha256(reinterpret(UInt8, vec(rawview(channelview(img))))))
```

```diff
# 0.6.1
24d5be33008cdfbc38845b2e5929b90db693ac203f9bf0fea76e39d45746f798
# 0.7.0
39869ae780dc1242d3e223a83b8ddadd868c1503b65de44dc5e5e5b2022da9cd
```

c.f. https://github.com/Evizero/ReferenceTests.jl/pull/46

**Comment by kimikage** [comment]
I'm checking just to be sure, but this is not the difference on `Normed`-->`Float64` conversions, right?

**Comment by johnnychen94** [comment]
> this is not the difference on Normed-->Float64 conversions, right?

You got it! I really should have checked that yesterday.

**Comment by kimikage** [comment]
> Should users be worried about this?

I think it depends on the usage or purpose. For example, it can be problematic in the tamper detection or  steganography. However, I don't think it is necessary to reduce accuracy for the compatibility. In any case, ReferenceTests.jl is working correctly.

**Comment by johnnychen94** [comment]
Could you point me to the PR where the behavior of `N0f8`->`Float64` is changed? I'm still curious about that.

**Comment by kimikage** [comment]
PR #138 (and PR #145)
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/402e637ce7841adb44c88f042645010db6da2fa5/src/normed.jl#L170-L179

**Comment by johnnychen94** [comment]
These lines are spells to me but I trust that's making things better 😃 . I'm closing this now.
