### ISSUE TITLE
[RFC] Changing the promotion type of `Integer` and `Fixed` to a float type.

### ISSUE THREAD

**Issue by kimikage** [JuliaMath/FixedPointNumbers.jl#192]
I was considering introducing `checked_mul` for Issue #78. However, I noticed that there are differences in promotion rules between `Fixed` and `Normed`.

```julia
julia> 2 * 0.5N2f14 # promotion to Float32
1.000061f0

julia> 2 * 0.5Q1f14 # promotion to Q1f14 (issue #78)
ERROR: ArgumentError: Fixed{Int16,14} is a 16-bit type representing 65536 values from -2.0 to 1.99994; cannot represent 2
```

Perhaps this is due to the current (historical) implementation where `Fixed` is signed and `Normed` is unsigned, but IMO, it seems practical to promote them to float types, and not to add `::Integer * ::FixedPoint`.

**Comment by kimikage** [comment]
The rules for `AbstractFloat` are also subtly different. I think the `Normed`'s rule is better.
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/7c90fb6b48867ff2fda1608b0b9c5b140e0ad963/src/fixed.jl#L197
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/7c90fb6b48867ff2fda1608b0b9c5b140e0ad963/src/normed.jl#L310

**Comment by kimikage** [comment]
If we decide to commonize the promotion rules, i.e. both `Fixed` and `Normed` are promoted to a float type for `Integer`, it seems to be "neutral" and practical that the promotion rule between `Fixed` and `Normed` returns a float types. (cf. #126)

**Comment by timholy** [comment]
Yes, we should go with the one used for Normed.

```julia
julia> x = rand(N0f32)
0.3137734384N0f32

julia> promote(x, Float16(1.0))
(0.3137734384075211, 1.0)

julia> x = rand(Q1f30)
-1.7184696067Q1f30

julia> promote(x, Float16(1.0))
(Float16(-1.719), Float16(1.0))
```

**Comment by kimikage** [comment]
I also want to commonize the following rules with https://github.com/JuliaMath/FixedPointNumbers.jl/issues/192#issuecomment-657059118.
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/0446a890170a321d47684aa19e3919ff86589f71/src/fixed.jl#L200-L213

Also, I'm thinking of removing the `@generated`. It seems that the promotion result can be inferred by replacing the `for` loop with recursion.

Please note that this is a "general purpose" promotion rule and we can design the promotion rules  for the arithmetic operations separately.

**Comment by timholy** [comment]
Yes, in general my view is that `promote` is not entirely adequate, because "promote for what?" is a relevant question. I've personally decided that `promote` really means "promote for `cat`", meaning it computes a single concrete type used as the eltype of a container that can store both objects.

**Comment by kimikage** [comment]
Even in `Normed`, there are cases where conversion can be performed fast and losslessly, e.g. `N0f8` to `N0f16`.

`Integer`s as promotion targets are often `Int`s i.e. with 32-bit or greater width, whereas `FixedPoint` is usually 8-bit or 16-bit. We're avoiding `Float16`, so I think the promotion to `floattype` is often overkill.

I prefer to apply the same promotion policy for the `Fixed` types and the `Normed` types.

**Comment by kimikage** [comment]
WIP: https://github.com/JuliaMath/FixedPointNumbers.jl/compare/master...kimikage:promotion_rule
This requires `nbitsint`, which is going to be introduced in PR #189, to support mixing `signed` and `unsigned` (NOT `Fixed` and `Normed`)
