### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by nico202** [JuliaMath/FixedPointNumbers.jl#240]
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/6236e668fffcefc0a98a68c7a1c65ffbbd92e978/test/fixed.jl#L59

I'm running julia 1.5.3.  When running  `zero(Fixed{Int8,8})`, no deprecation error is thrown

**Comment by kimikage** [comment]
In Julia v1.5, the default for the `--depwarn` option has been changed to `no`. You can probably see the warning with `--depwarn=yes`.

**Comment by nico202** [comment]
Oh ok thanks, did not think about that!
