### ISSUE TITLE
Move to JuliaMath?

### ISSUE THREAD

**Issue by timholy** [JuliaMath/FixedPointNumbers.jl#50]
Any interest in moving this package to JuliaMath? Orgs have pluses and minuses, but on balance they seem to be recommended for key pieces of infrastructure (which this definitely is).

**Comment by tlnagy** [comment]
I think this is a good idea, what are the minuses?

**Comment by timholy** [comment]
Sometimes a minus is that no one feels responsible. Back when HDF5 and JLD were under my name, I felt responsible for fixing bugs (or shamed by not fixing them). Now that those packages are under a generic umbrella, I no longer feel appreciable guilt about letting bugs rot forever. (I fix the ones that affect me personally, but I figure it's up to others to fix the bugs that affect them.) That's good for me but bad for HDF5/JLD. (The alternative is also just not practical, since I already maintain too many packages.)

But really this is @JeffBezanson's decision, and indeed no one but him can actually make the transfer (barring someone transferring a fork).

**Comment by tlnagy** [comment]
That's valid criticism. I guess that never occurred to me (haven't had that much experience developing open source software). I really hope pushing everyone to have tests and checking the whole ecosystem via PkgEvaluator means that it's easier to identify problem packages and get those fixed. Maybe it will help with the problem of extensive code rot in OSS.

**Comment by vchuravy** [comment]
I would be fine with moving this to JuliaMath, but in the end it is really up to Jeff if he wants to give up his only Julia package under his own name ;)

**Comment by JeffBezanson** [comment]
I'm fine with moving it; probably makes sense since mostly folks other than me have been maintaining it. If I want to own a package I'll have to come up with something else :)

**Comment by timholy** [comment]
Definitely your call, and I have zero objections to you keeping it under your name (but if so please do turn on AppVeyor).

**Comment by timholy** [comment]
Oh, and in case this package stuff is unfamiliar, here's a cheat sheet:
- If you want to keep it here, I think you can turn on AppVeyor just by going to https://www.appveyor.com/, logging in, and adding the project. I added the other necessary component, `appveyor.yml`, in 05373816d2f3e1a92c921b81283a4bbaaa44bcc8.
- If you want to transfer it, I think you need to be an owner for JuliaMath. In case that's the route you prefer, I just added you. In this repo, you would need to click "Settings," then scroll down to the bottom of the page, and select "Transfer Ownership."

**Comment by JeffBezanson** [comment]
Done.
