### ISSUE TITLE
Fixed8, Fixed16, etc.

### ISSUE THREAD

**Issue by ssfrr** [JuliaMath/FixedPointNumbers.jl#57]
In audio it's common to use signed integer samples, which in FixedPointNumbers parlance becomes `Fixed{Int16, 15}` for 16-bit samples, or `Fixed{Int8, 7}` for 8-bit.

For my use cases, aliases like `Fixed8`, `Fixed16` with the above definitions would be useful, but I see there's already a definition for `Fixed16` to `Fixed{Int32, 16}`, and a deprecated `Fixed32` that aliases to the current `Fixed16` definition.

Would these definitions also work for the use-cases currently using the `Fixed16` definition, or do they need the extra storage space for values outside [-1, 1)?

**Comment by timholy** [comment]
The current aliases are likely to be deprecated in favor of more flexible ones, see #51.

**Comment by vchuravy** [comment]
I think this can be closed?
