### ISSUE TITLE
typealiases missing?

### ISSUE THREAD

**Issue by rsrock** [JuliaMath/FixedPointNumbers.jl#67]
These are mentioned in the README, but don't appear to be there?

```
julia> using FixedPointNumbers

julia> Normed8
UndefVarError: Normed8 not defined

julia> Normed{UInt8, 8}
FixedPointNumbers.Normed{UInt8,8}
```

**Comment by timholy** [comment]
I wonder if this was a `sed`-like error in #63?

**Comment by vchuravy** [comment]
Just a mistake on my part when updating the README. I will fix that today.
